---
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.0.2.2:1521/XE
    username: hr
    password: welcome1
    driverClassName: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true

oracle:
  url: jdbc:oracle:thin:@//10.0.2.2:1521/XE
  username: hr
  password: welcome1

server:
  port: 9005

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/