---
spring:
  datasource:
    url: jdbc:oracle:thin:@//10.0.2.2:1521/XE
    username: hr
    password: welcome1
    driverClassName: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true

oracle:
  url: jdbc:oracle:thin:@//10.0.2.2:1521/XE
  username: hr
  password: welcome1

server:
  port: 9005

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/
      
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.1.2.20
          defaultBrokerPort: 9092
          zkNodes: 10.1.2.20
          defaultZkPort: 2181
          zkConnectionTimeout: 100000
      bindings:
        output:
          destination: test4
          content-type: application/json
          
