---
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: welcome1
    driverClassName: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true


server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/