---
server:
  port: 89890

management:
  port: 89900

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/
      
turbine:
  appConfig: get-submissions
  clusterNameExpression: metadata['submissions']
