info:
  component: Turbine Server
  
server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: yes
    fetchRegistry: yes
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/
      
turbine:
  aggregator:
    clusterConfig: GET-SUBMISSIONS
  appConfig: get-submissions
