info:
  component: Zuul Server

zuul:
  routes:
    get-submissions:
      path: /submissions/**
      serviceId: get-submissions
      stripPrefix: false
      
    
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: yes
    fetchRegistry: yes
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/
      
ribbon:
  eureka:
    enabled: false

users:
  ribbon:
    listOfServers: http://10.1.2.41:9005,http://10.1.2.42:9005

server:
  port: 9766

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
