info:
  component: Zuul Server

zuul:
  routes:
    sub:
      path: /sub/**
      serviceId: get-submissions
      

ribbon:
  eureka:
    enabled: false

sub:
  ribbon:
    listOfServers: http://10.1.2.41:9005/sub/,http://10.1.2.42:9005/sub/
    
    
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/

server:
  port: 9765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
