info:
  component: Zuul Server

zuul:
  ignoredServices: "*"
  routes:
    sub:
      path: /submissions/**
#      stripPrefix: false

ribbon:
  eureka:
    enabled: true
    
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/

server:
  port: 9765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
