info:
  component: Zuul Server

zuul:
  routes:
    get-submissions: /submissions/**
    
      
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 50000
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: yes
    fetchRegistry: yes
    serviceUrl:
      defaultZone: http://10.1.2.32:8761/eureka/,http://10.1.2.33:8761/eureka/

server:
  port: 9766

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
